apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: kube-prometheus-app
  namespace: argocd
spec: 
  destination: 
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  project: my-project
  source: 
    chart: kube-prometheus-stack
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: 51.2.0
    helm:
     releaseName: kube-prometheus-stack
  syncPolicy:
    syncOptions:
      - CreateNamespace=true