apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: openim-dependencies-app
  namespace: argocd
spec: 
  destination: 
    namespace: openim-dependencies
    server: "https://kubernetes.default.svc"
  project: openim-project
  sources: 
   - chart: mysql
     repoURL: "https://charts.bitnami.com/bitnami"
     targetRevision: 9.12.3
     helm:
      releaseName: openim-mysql
      # valueFiles:
      # - $values/mysql/values.yaml
   - chart: redis
     repoURL: "https://charts.bitnami.com/bitnami"
     targetRevision: 18.1.2
     helm:
      releaseName: openim-redis
      valueFiles:
      - $values/redis/values.yaml
   - chart: mongodb
     repoURL: "https://charts.bitnami.com/bitnami"
     targetRevision: 14.0.5
     helm:
      releaseName: openim-mongodb
      # valueFiles:
      # - $values/mongodb/values.yaml
   - chart: kafka
     repoURL: "https://charts.bitnami.com/bitnami"
     targetRevision: 25.3.1
     helm:
      releaseName: openim-kafka
      # valueFiles:
      # - $values/kafka/values.yaml
   - chart: zookeeper
     repoURL: "https://charts.bitnami.com/bitnami"
     targetRevision: 12.1.3
     helm:
      releaseName: openim-zookeeper
      # valueFiles:
      # - $values/zookeeper/values.yaml
   - chart: minio
     repoURL: "https://charts.bitnami.com/bitnami"
     targetRevision: 12.8.12
     helm:
      releaseName: openim-minio
      # valueFiles:
      # - $values/minio/values.yaml
   - chart: etcd
     repoURL: "https://charts.bitnami.com/bitnami"
     targetRevision: 9.5.1
     helm:
      releaseName: openim-etcd
      # valueFiles:
      # - $values/etcd/values.yaml
   - repoURL: "https://github.com/truongpx396/open-im-server-k8s-deploy.git"
     ref: values
     targetRevision: main
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # - ServerSideApply=true