apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: openim-management
  namespace: argocd
spec: 
  destination: 
    namespace: openim-management
    server: "https://kubernetes.default.svc"
  project: openim-project
  sources: 
   - path: open-im-management-chat/config-chart
     repoURL: "https://github.com/truongpx396/open-im-server-k8s-deploy.git"
     targetRevision: main
     helm:
      releaseName: config
   - path: open-im-management-chat/api-admin
     repoURL: "https://github.com/truongpx396/open-im-server-k8s-deploy.git"
     targetRevision: main
   - path: open-im-management-chat/api-chat
     repoURL: "https://github.com/truongpx396/open-im-server-k8s-deploy.git"
     targetRevision: main
   - path: open-im-management-chat/rpc-admin
     repoURL: "https://github.com/truongpx396/open-im-server-k8s-deploy.git"
     targetRevision: main
   - path: open-im-management-chat/rpc-chat
     repoURL: "https://github.com/truongpx396/open-im-server-k8s-deploy.git"
     targetRevision: main
  syncPolicy:
    automated: 
      prune: true
    syncOptions:
      - CreateNamespace=true